# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 00:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170508_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='is_band',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
