# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 23:45
from __future__ import unicode_literals

from django.db import migrations
from utils.db import UpdateShowVersion

CONTINUITY_TYPES = {
    'FOUNTAIN': 'fountain',
    'FORWARD': 'fm',
    'STOP': None,
    'EVEN': 'even',
    'DIAGONAL': 'diagonal',
    'FTL': 'ftl',
    'CM': 'cm',
    'TWO': 'two',
    'GATE': 'gate',
    'GRAPEVINE': 'gv',
}

def update_continuity(continuity):
    _type = continuity['type']

    if _type == 'STOP':
        if not continuity['isMarkTime']:
            _type = 'close'
        elif continuity['duration'] is None:
            _type = 'mtrm'
        else:
            _type = 'mt'
    else:
        _type = CONTINUITY_TYPES[_type]

    if _type == 'two':
        for c in continuity['continuities']:
            update_continuity(c)

    continuity['type'] = _type

def update_version(show):
    for sheet in show['sheets']:
        for dot_type_continuities in sheet['continuities'].values():
            for continuity in dot_type_continuities:
                update_continuity(continuity)

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_show_fields'),
    ]

    operations = [
        UpdateShowVersion(2, update_version),
    ]
