# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 23:45
from __future__ import unicode_literals

from django.db import migrations
from utils.db import UpdateShowVersion

def update_version(show):
    for sheet in show['sheets']:
        sheet['continuities']['all-before'] = []
        sheet['continuities']['all-after'] = []

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_version_2'),
    ]

    operations = [
        UpdateShowVersion(3, update_version),
    ]
