# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 23:45
from __future__ import unicode_literals

from django.db import migrations
from utils.db import UpdateShowVersion

def update_continuity(continuity):
    _type = continuity['type']

    if _type == 'mtrm':
        continuity['type'] = 'mt'
        continuity['duration'] = None

    if _type == 'two':
        for c in continuity['continuities']:
            update_continuity(c)

def update_version(show):
    for sheet in show['sheets']:
        for dot_type_continuities in sheet['continuities'].values():
            for continuity in dot_type_continuities:
                update_continuity(continuity)

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_version_3'),
    ]

    operations = [
        UpdateShowVersion(4, update_version),
    ]
