# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_version_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='members_only_username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
