# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 10:44
from __future__ import unicode_literals

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_version_7'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', base.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='show',
            name='data_file',
            field=models.FileField(upload_to='shows'),
        ),
    ]
