#!/usr/bin/env bash

set -e

echo "Putting calchart-prod into maintenance mode..."
heroku maintenance:on -a calchart-prod

echo "Promoting pipeline..."
heroku pipelines:promote -a calchart-staging

echo "Running post_promote script"
heroku run source bin/post_promote -a calchart-prod && (
    echo "Taking calchart-prod off maintenance mode..."
    heroku maintenance:off -a calchart-prod
)
